In [9]:
import numpy as np
arr =np.array([1,2,3,4,5,6,7,8,9])
arr

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [10]:
prices =[10,20,30,40,50]
price_arrary =np.array(prices)
price_array

array([10, 20, 30, 40, 50])

In [12]:
#single dimension array
names =["karthik",'hari','sanjeev','govardhan']
name_array =np.array(names)
name_array

array(['karthik', 'hari', 'sanjeev', 'govardhan'], dtype='<U9')

In [13]:
name_array[0]


np.str_('karthik')

In [15]:
#multi dimension array
multi_array =np.array([[1,2,3],[4,5,6]])
multi_array


array([[1, 2, 3],
       [4, 5, 6]])

In [19]:
multi_array[0][1]


np.int64(2)

In [20]:
multi_array.ndim

2

In [22]:
name_array.ndim

1

In [23]:
multi_array.dtype


dtype('int64')

In [24]:
name_array.dtype

dtype('<U9')

In [31]:
#creating array & type conversation 
auto_array=np.zeros(10)
#auto_array.np.ones(10)
auto_array

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [32]:
 auto_array.dtype

dtype('float64')

In [35]:
auto_array =auto_array.astype(np.int64)
auto_array

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [37]:
array =np.array([1,2,3,4],dtype =np.float64)
array

array([1., 2., 3., 4.])

In [38]:
array.dtype

dtype('float64')

In [40]:
array.astype(np.int64)

array([1, 2, 3, 4])

In [43]:
array =array.astype(np.int64)


In [74]:
array

array([1, 2, 3, 4])

In [77]:
# arithmatic operations on array
import numpy as np
list_a =[[1,2,3],[4,5,6]]
list_b =[[7,8,9],[10,11,12]]
array_a = np.array(list_a)
array_b =np.array(list_b)


In [78]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [76]:
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [72]:
array_a+array_b

array([[14, 16, 18],
       [20, 22, 24]])

In [71]:
array_b-array_a

array([[0, 0, 0],
       [0, 0, 0]])

In [57]:
array_a*array_b

array([[ 7, 16, 27],
       [40, 55, 72]])

In [58]:
array_b/array_a

array([[7. , 4. , 3. ],
       [2.5, 2.2, 2. ]])

In [80]:
#scalar multiplication
array_a *2


array([[ 2,  4,  6],
       [ 8, 10, 12]])

In [81]:
array_a

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [83]:
#scalar divison
array_b /10

array([[0.7, 0.8, 0.9],
       [1. , 1.1, 1.2]])

In [85]:
#comparing arrays
array_a


array([[1, 2, 3],
       [4, 5, 6]])

In [86]:
array_b

array([[ 7,  8,  9],
       [10, 11, 12]])

In [93]:
res=array_a>>array_b
res.dtype

dtype('int64')

In [95]:
#indexing &slicing array
import numpy as np
arr =np.array([10,20,30,40,50])
arr

array([10, 20, 30, 40, 50])

In [96]:
arr[0]

np.int64(10)

In [97]:
arr =np.array([[1,2,3],[4,5,6]])
arr

array([[1, 2, 3],
       [4, 5, 6]])

In [114]:
arr[0,[1]]

array([2])

In [121]:
#slicing foa an array
arr =np.array([10,20,30,40,50,60,70])
arr

array([10, 20, 30, 40, 50, 60, 70])

In [122]:
arr[1:5]

array([20, 30, 40, 50])

In [123]:
multi_array =np.array([[1,2,3],[4,5,6],[7,8,9]])
multi_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [125]:
multi_array[1:3]

array([[4, 5, 6],
       [7, 8, 9]])

In [126]:
multi_array[1:3,1:2]

array([[5],
       [8]])

In [10]:
#fancy indexing & Boolean Indexing
import numpy as np
multi_array =np.array([[1,2,3],[4,5,6],[7,8,9]])
multi_array


array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [11]:
multi_array[[0,0,0,2],[0,2,0,2]]

array([1, 3, 1, 9])

In [12]:
multi_array[multi_array>5]

array([6, 7, 8, 9])

In [17]:
#creating series from pandas
from pandas import Series
s =Series([1,2,3,4,5,6,7,8,9])
s

0    1
1    2
2    3
3    4
4    5
5    6
6    7
7    8
8    9
dtype: int64

In [18]:
s[3]

np.int64(4)

In [19]:
s.values

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
s.index

RangeIndex(start=0, stop=9, step=1)

In [23]:
s  =Series([100,200,300],index=[1,2,3,])
s

1    100
2    200
3    300
dtype: int64

In [24]:
s  =Series([100,200,300],index=[7,8,9])
s

7    100
8    200
9    300
dtype: int64

In [28]:
#instead of  int index giving strings
s  =Series([100,200,300],index=['a','b','c'])
s

a    100
b    200
c    300
dtype: int64

In [30]:
s['c']

np.int64(300)

In [32]:
#another thing about Series is that you could also go ahead and create a series from a Python dictionary
#a dictionary we typically have values in terms of a key value pair.
s=Series({'a':'Karthik','b':100})
s
#from this dictionary where all the key values are translated into index values.
#All the value pairs are actually translated into the values or elements stored inside that particular series


a    Karthik
b        100
dtype: object

In [34]:
# Method & attributes from pandas
from pandas import Series
s =Series([10,20,30,40,50,60,70,80,90])
s

0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64

In [35]:
s.sum()


np.int64(450)

In [36]:
s.product()

np.int64(362880000000000)

In [57]:
# s.nbytes
# s.size
# s.loc
# # s.agg

s.mod

<bound method Series.mod of 0    10
1    20
2    30
3    40
4    50
5    60
6    70
7    80
8    90
dtype: int64>

In [58]:
s.dtypes

dtype('int64')

In [59]:
s.size

9

In [61]:
s.values

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [62]:
type(s.values)

numpy.ndarray

In [66]:
#A DataFrame is a two-dimensional, size-mutable, and potentially heterogeneous tabular data structure with labeled axes (rows and columns).
# It is one of the primary data structures provided by the Pandas library in Python, widely used for data manipulation, analysis, and cleaning.
# You can think of a DataFrame as a table (similar to an Excel spreadsheet or a SQL table), where the data is organized in rows and columns.

# data frame is nothing but it's another data structure which is provided by pandas which we could use to load data from a data source.
#data frame as a standalone entity or as a standalone object.
from  pandas import DataFrame
people = {'name':['karthik','hari','govardhan','sanjeeva','vikas'],'age':[22,20,28,29,24],'Location':["UK","BN","HY","TY","MM"]}
frame =DataFrame(people)
frame

name  age Location
0    karthik   22       UK
1       hari   20       BN
2  govardhan   28       HY
3   sanjeeva   29       TY
4      vikas   24       MM

In [4]:
from  pandas import DataFrame
people = {'name':['karthik','hari','govardhan','sanjeeva','vikas'],'age':[22,20,28,29,24],'Location':["UK","BN","HY","TY","MM"]}
frame =DataFrame(people,columns=['name','Location','age','salary'])
frame

name Location  age salary
0    karthik       UK   22    NaN
1       hari       BN   20    NaN
2  govardhan       HY   28    NaN
3   sanjeeva       TY   29    NaN
4      vikas       MM   24    NaN

In [5]:
frame["Location"]


0    UK
1    BN
2    HY
3    TY
4    MM
Name: Location, dtype: object

In [74]:
frame.Location

0    UK
1    BN
2    HY
3    TY
4    MM
Name: Location, dtype: object

In [77]:
# this lock over here is a data frame attribute which actually allows us to select a data inside a pandas data frame.
frame.loc[1]



name        hari
Location      BN
age           20
salary       NaN
Name: 1, dtype: object

In [78]:
frame

name Location  age salary
0    karthik       UK   22    NaN
1       hari       BN   20    NaN
2  govardhan       HY   28    NaN
3   sanjeeva       TY   29    NaN
4      vikas       MM   24    NaN

In [6]:
frame.salary = 200
frame

name Location  age  salary
0    karthik       UK   22     200
1       hari       BN   20     200
2  govardhan       HY   28     200
3   sanjeeva       TY   29     200
4      vikas       MM   24     200

In [7]:
# cleanse up this undefined data from a data frame.
from pandas import Series
salaries =Series([1000,2000,3000,4000,5000])
frame.salary =salaries
frame

name Location  age  salary
0    karthik       UK   22    1000
1       hari       BN   20    2000
2  govardhan       HY   28    3000
3   sanjeeva       TY   29    4000
4      vikas       MM   24    5000

In [8]:
del frame['salary']
frame

name Location  age
0    karthik       UK   22
1       hari       BN   20
2  govardhan       HY   28
3   sanjeeva       TY   29
4      vikas       MM   24

In [17]:
#Re-indexing 
#Re-indexing basically means a rearranging the indexes of the data frames or a series, which we have.
from pandas import Series
s = Series([10,20,30,40,50], index=['c','d','e','b','a'])
s

c    10
d    20
e    30
b    40
a    50
dtype: int64

In [18]:
s=s.reindex(['a','b','c','d','e'])
s

a    50
b    40
c    10
d    20
e    30
dtype: int64

In [26]:
from pandas import DataFrame
import numpy as np
d = DataFrame(np.arange(9).reshape((3,3)), index=['c','b','a'], columns=['apple','banana','mango'])
d                    

apple  banana  mango
c      0       1      2
b      3       4      5
a      6       7      8

In [33]:
d=d.reindex(['a','b','c'])
d

apple  banana  mango
a      6       7      8
b      3       4      5
c      0       1      2

In [32]:
d.reindex(columns=['mango','banana','apple'])

mango  banana  apple
a      8       7      6
b      5       4      3
c      2       1      0

In [37]:
#Arithmetic Operations With Fill Values
from pandas import Series
s1=Series([1,2,3,4,5], index=['a','b','c','d','e'])
s2= Series([1,2,3,4,5,6,7],index=['a','b','c','d','e','f','g'])

s1


a    1
b    2
c    3
d    4
e    5
dtype: int64

In [38]:
s2

a    1
b    2
c    3
d    4
e    5
f    6
g    7
dtype: int64

In [39]:
s1+s2

a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
f     NaN
g     NaN
dtype: float64

In [40]:
s1.add(s2)


a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
f     NaN
g     NaN
dtype: float64

In [43]:
s1.add(s2,fill_value=0)


a     2.0
b     4.0
c     6.0
d     8.0
e    10.0
f     6.0
g     7.0
dtype: float64

In [50]:
from pandas import DataFrame
import numpy as np
d1 = DataFrame(np.arange(12).reshape(3,4),columns=['a','b','c','d'])
d2 = DataFrame(np.arange(16).reshape(4,4),columns=['a','b','c','d'])

In [51]:
d1

a  b   c   d
0  0  1   2   3
1  4  5   6   7
2  8  9  10  11

In [52]:
d2

a   b   c   d
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [53]:
d1+d2

a     b     c     d
0   0.0   2.0   4.0   6.0
1   8.0  10.0  12.0  14.0
2  16.0  18.0  20.0  22.0
3   NaN   NaN   NaN   NaN

In [54]:
d1.add(d2, fill_value=0)

a     b     c     d
0   0.0   2.0   4.0   6.0
1   8.0  10.0  12.0  14.0
2  16.0  18.0  20.0  22.0
3  12.0  13.0  14.0  15.0

In [56]:
#Adding Series & Dataframe
from pandas import DataFrame , Series
import numpy as np
s = Series([1,2,3,4])
d =DataFrame(np.arange(8).reshape(2,4))

In [57]:
s


0    1
1    2
2    3
3    4
dtype: int64

In [58]:
d

0  1  2  3
0  0  1  2  3
1  4  5  6  7

In [59]:
s+d

0  1  2   3
0  1  3  5   7
1  5  7  9  11

In [60]:
#Function Application & Mapping
from pandas import DataFrame
d =DataFrame(np.arange(16).reshape(4,4))
d


0   1   2   3
0   0   1   2   3
1   4   5   6   7
2   8   9  10  11
3  12  13  14  15

In [61]:
#function add to dataframe
f = lambda x: x+10
d.apply(f)

0   1   2   3
0  10  11  12  13
1  14  15  16  17
2  18  19  20  21
3  22  23  24  25

In [63]:
#function add to dataframe
f2 = lambda x: x*x
d.apply(f2)

0    1    2    3
0    0    1    4    9
1   16   25   36   49
2   64   81  100  121
3  144  169  196  225

In [64]:
#Sorting& Ranking
from pandas import Series
s =Series([1,2,3,4,5],index=['e','c','b','d','a'])
s


e    1
c    2
b    3
d    4
a    5
dtype: int64

In [65]:
s.sort_index()

a    5
b    3
c    2
d    4
e    1
dtype: int64

In [66]:
from pandas import DataFrame
import numpy as np
d = DataFrame(np.arange(9).reshape((3,3)), index=['c','b','a'])
d

0  1  2
c  0  1  2
b  3  4  5
a  6  7  8

In [67]:
d.sort_index()

0  1  2
a  6  7  8
b  3  4  5
c  0  1  2

In [72]:
from pandas import DataFrame
import numpy as np
d = DataFrame(np.arange(16).reshape((4,4)), index=[3,1,4,2],columns=['d','c','b','a'])
d

d   c   b   a
3   0   1   2   3
1   4   5   6   7
4   8   9  10  11
2  12  13  14  15

In [73]:
d.sort_index()

d   c   b   a
1   4   5   6   7
2  12  13  14  15
3   0   1   2   3
4   8   9  10  11

In [76]:
d.sort_index(axis=1,ascending=False)

d   c   b   a
3   0   1   2   3
1   4   5   6   7
4   8   9  10  11
2  12  13  14  15

In [77]:
d.sort_index(ascending=False)

d   c   b   a
4   8   9  10  11
3   0   1   2   3
2  12  13  14  15
1   4   5   6   7

In [83]:
from pandas import Series
price =Series([200,700,500,300,900,600])
price

0    200
1    700
2    500
3    300
4    900
5    600
dtype: int64

In [84]:
price.sort_values()

0    200
3    300
2    500
5    600
1    700
4    900
dtype: int64

In [86]:
price

0    200
1    700
2    500
3    300
4    900
5    600
dtype: int64

In [89]:

#from pandas import DataFrame
products =DataFrame({'name':['phone','laptop','tablet'],'price':[2000,4000, 1000]})
products

name  price
0   phone   2000
1  laptop   4000
2  tablet   1000

In [92]:
products.sort_values(by='price',ascending = False)

name  price
1  laptop   4000
0   phone   2000
2  tablet   1000

In [93]:
s = Series([1,2,3,4,5,6,7], index =['a','b','c','d','e','a','b'])
s

a    1
b    2
c    3
d    4
e    5
a    6
b    7
dtype: int64

In [96]:
s = Series([1,2,3,4,5,6,7], index =['a','b','c','d','e','a','b'])
s

a    1
b    2
c    3
d    4
e    5
a    6
b    7
dtype: int64

In [97]:
s.index.is_unique

False

In [100]:
s.is_unique

True

In [101]:
products.sum()

name     phonelaptoptablet
price                 7000
dtype: object

In [102]:
products.count()

name     3
price    3
dtype: int64

In [104]:
products.describe()

price
count     3.000000
mean   2333.333333
std    1527.525232
min    1000.000000
25%    1500.000000
50%    2000.000000
75%    3000.000000
max    4000.000000

In [109]:
# to remove nan values form series
from pandas import Series
import numpy as np
s =Series([1,2,np.nan,4,np.nan,6,np.nan])
s

0    1.0
1    2.0
2    NaN
3    4.0
4    NaN
5    6.0
6    NaN
dtype: float64

In [110]:
s.dropna()

0    1.0
1    2.0
3    4.0
5    6.0
dtype: float64

In [31]:
from pandas import DataFrame
import numpy as np
data =DataFrame([[1,2,3],[np.nan,np.nan,np.nan],[2,np.nan,4],[np.nan,3,np.nan]])
data

0    1    2
0  1.0  2.0  3.0
1  NaN  NaN  NaN
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [32]:
data.dropna(how ='all')

0    1    2
0  1.0  2.0  3.0
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [33]:
data.dropna(how ='all',axis=1)

0    1    2
0  1.0  2.0  3.0
1  NaN  NaN  NaN
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [34]:

data

0    1    2
0  1.0  2.0  3.0
1  NaN  NaN  NaN
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [35]:
data.dropna(how ='all')

0    1    2
0  1.0  2.0  3.0
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [36]:
data.dropna(how ='all',axis=1)

0    1    2
0  1.0  2.0  3.0
1  NaN  NaN  NaN
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [37]:
data.dropna(how ='all')


0    1    2
0  1.0  2.0  3.0
2  2.0  NaN  4.0
3  NaN  3.0  NaN

In [38]:
data.fillna(0)

0    1    2
0  1.0  2.0  3.0
1  0.0  0.0  0.0
2  2.0  0.0  4.0
3  0.0  3.0  0.0

In [43]:
from pandas import DataFrame, Series
import numpy as np
s1 = Series(np.arange(10),index=[['a','a','b','b','b','c','c','d','e','e'],[1,2,1,2,3,1,2,1,1,2]])
s1

a  1    0
   2    1
b  1    2
   2    3
   3    4
c  1    5
   2    6
d  1    7
e  1    8
   2    9
dtype: int64

In [44]:
s1['b'][3]

np.int64(4)

In [45]:
s1.index

MultiIndex([('a', 1),
            ('a', 2),
            ('b', 1),
            ('b', 2),
            ('b', 3),
            ('c', 1),
            ('c', 2),
            ('d', 1),
            ('e', 1),
            ('e', 2)],
           )

In [46]:
s1['b']

1    2
2    3
3    4
dtype: int64

In [48]:
s1['a':'c']

a  1    0
   2    1
b  1    2
   2    3
   3    4
c  1    5
   2    6
dtype: int64

In [49]:
s1.unstack()

1    2    3
a  0.0  1.0  NaN
b  2.0  3.0  4.0
c  5.0  6.0  NaN
d  7.0  NaN  NaN
e  8.0  9.0  NaN

In [56]:
from pandas import DataFrame, Series
import numpy as np
data_frame =DataFrame(np.arange(15).reshape(5,3),index=['a','b','c','d','e'])
data_frame

0   1   2
a   0   1   2
b   3   4   5
c   6   7   8
d   9  10  11
e  12  13  14

In [57]:
data_frame.stack()

a  0     0
   1     1
   2     2
b  0     3
   1     4
   2     5
c  0     6
   1     7
   2     8
d  0     9
   1    10
   2    11
e  0    12
   1    13
   2    14
dtype: int64

In [72]:
from pandas import Series
s=Series(index=[1000,1001,1002,1003],data=['laptop','tablet','phone','computer'])
s

1000      laptop
1001      tablet
1002       phone
1003    computer
dtype: object

In [2]:
from pandas import Series
stock_symbols = {"ltimindtree ltd":"LTIM","anton computers":"ANT","acme corp":"ACMC"}
stock_prices ={"LTIM":37,"ACMC":80,"ANT":50}
symbol_series = Series(stock_symbols)
price_series =Series(stock_prices)


In [3]:
symbol_series

ltimindtree ltd    LTIM
anton computers     ANT
acme corp          ACMC
dtype: object

In [4]:
price_series

LTIM    37
ACMC    80
ANT     50
dtype: int64

In [5]:
symbol_series.map(price_series)

ltimindtree ltd    37
anton computers    50
acme corp          80
dtype: int64